name: Staging CI

on:
  push:
    branches:
      - staging

jobs:
  lint_helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint Helm
        run: helm lint ./charts/fbw-website
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: flybywiresim/website
          tag-sha: true
          tag-latest: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=flybywiresim/website:latest
          cache-to: type=inline
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  deploy_staging:
    runs-on: ubuntu-latest
    needs: [build_and_push, lint_helm]
    env:
      NAMESPACE: fbw-website-staging
      RELEASE_NAME: fbw-website-staging
      VALUES_FILE: ./charts/fbw-website/environments/staging.yaml
    steps:
      - uses: actions/checkout@v1
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ${{ secrets.DIGITALOCEAN_CLUSTER_ID }}
      - name: Deploy
        run: |
          TAG=$(echo $GITHUB_SHA | head -c7) &&
          helm upgrade --namespace ${NAMESPACE} --set image.tag=sha-${TAG} \
          -f ./charts/fbw-website/values.yaml -f ${VALUES_FILE} ${RELEASE_NAME} ./charts/fbw-website
